name: "Running tests: style, pytests and entry-points"

on:
  push:
    branches: [ "main", "test"]
  pull_request:
    branches: [ "main", "test"]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: gt4sd-molformer
            environment-file: conda.yml
            auto-activate-base: false
            use-only-tar-bz2: true
