name: "Running tests: style, pytests and entry-points"

on:
  push:
    branches: [ "main", "test"]
  pull_request:
    branches: [ "main", "test"]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        shell: bash -l {0} # for conda command
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
          with:
            activate-environment: gt4sd-molformer
            environment-file: conda.yml
            auto-activate-base: false
            use-only-tar-bz2: true
      - name: Install dependencies
        run: |
          python -m pip install pip<=22.3.1
          python -m pip install flake8 pytest black isort mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install gt4sd-molformer from source
        run: |
          pip install .
      - name: Check black
        run: |
          python -m black src/gt4sd --check --diff --color
      - name: Check isort
        run: |
          python -m isort src/gt4sd --check-only
      - name: Check flake8
        run: |
          python -m flake8 --disable-noqa --per-file-ignores="__init__.py:F401" src/gt4sd
      - name: Check mypy
        run: |
          python -m mypy src/gt4sd